### ISSUE TITLE
Don't you mind that I adapted this code into my mod?

### ISSUE THREAD

**Issue by Craluminum2413** [Xytabich/Glassmaking#2]
https://github.com/Xytabich/Glassmaking/blob/0f8058dcdc9b2632476cc72e07c88dfbaebfb2ee/src/Items/ItemWettable.cs#L49-L81

this is my mod
https://github.com/Craluminum-Mods/ImmersiveCrafting/blob/dc8fb90bd81cc0f97995ca2b20533a4a2cd721e8/src/CollectibleBehavior/BehaviorUseOnBucket.cs#L82-L129

**Comment by Xytabich** [comment]
Feel free to use any code, that's why i'm uploading it here
