### ISSUE TITLE
recipe for glass blends?

### ISSUE THREAD

**Issue by kotoroshinoto** [Xytabich/Glassmaking#3]
handbook entry for glass making does not make the glass blend recipe obvious, and for some reason, the entries of the items don't show a recipe either.

**Comment by Xytabich** [comment]
Blends don't have a recipe, as they are made up of many ingredients that vanilla doesn't have, like potash. According to this blend recipes you can add yourself.

**Comment by kotoroshinoto** [comment]
how do you make blends when using the mod then?

**Comment by Xytabich** [comment]
Not quite understood what you mean.
How to add a custom blend described in the wiki, "Adding glass blend" section: https://xytabich.github.io/vintagestory/glassmaking/glasstype.html
If you need a recipe for vanilla types of glass, then you need to create them yourself based on the modpack present in the game, or to your taste. The Glassmaking mod basically adds only crafting mechanics and the most necessary tools. Everything else depends on the modpack.

**Comment by kotoroshinoto** [comment]
I see, so its probably a mod that isn't set up to work correctly with your interface that I'm trying to figure out.

I found a set of recipes with names like "[X] glass batch"

![image](https://user-images.githubusercontent.com/1337560/177006909-48ce523f-166a-4982-a4c3-5f70f1fd8d5d.png)


the colored ones use something called "frit" and tend to need borax/lime/bone powder etc.

do I just need to register these items with your system somehow or does the mod author have to do it?

**Comment by kotoroshinoto** [comment]
how does one find out what the item names/codes etc are? I assume there is a command for that?

edit: its most likely from Bricklayers. I'll read into your wiki and figure out how to add these items to the config.
where it says "To add your own glass type, you need to create a file assets/MODID/worldproperties/abstract/glasstype.json"

what subdirectory does that assets directory belong in?

**Comment by Xytabich** [comment]
I don't understand what directory you mean, `assets` is the directory at the root of the mod, and is used by default for all mod assets. The wiki provides a link to an example file with glass types. https://github.com/Xytabich/Glassmaking/blob/master/assets/game/worldproperties/abstract/glasstype.json

**Comment by kotoroshinoto** [comment]
if I add files to your mod, those wouldn't propagate to users connecting to the server would it?

I was under the impression that users downloaded from the mod-db rather than the server's own files.

Would it still work if it was server-side only?

**Comment by Xytabich** [comment]
These files are needed both on the server and on the client, so you will have to transfer your mod or modified glassmaking to other players on the server. I don't recommend changing the mod itself, as there are many undocumented things that can lead to errors.

**Comment by kotoroshinoto** [comment]
That is less than ideal. Vintage story's mod system is superior to ones like minecraft-forge precisely because it is integrated into the base game AND because the user doesn't have to configure anything under normal circumstances. They connect to the server, and the client goes to the mod-db for the mods.

Maybe if there was some way for this information to be parsed from the configs rather than directly nested in the mod zip that would work better? The server does send config information to the clients doesn't it?

I don't mean to be critical for the sake of it.

I personally am adept enough to write code, but a lot of my gaming friends are rather technology challenged. Trying to walk them through mod setup is rather painful, even if it simply is a matter of downloading files. It would be best to try to conform to the vintage story model of minimal user setup and inheriting as much from the server and mod-db through automated means as possible.

**Comment by Xytabich** [comment]
Parameters like those in `glasstype.json` are not synchronized by default, each parameter list has a network part to send/receive values, be it for recipes, items, blocks, etc.
For each type of glass from `glasstype.json` there must be a texture that must already be available on the client side. Therefore, it makes little sense to synchronize these parameters, since in any case you will have to give the zip to other players.

**Comment by kotoroshinoto** [comment]
is there no way to get the path to the texture from other already-existing mods, or is the idea to create entirely new mixtures as well?

Perhaps it would make sense for the modpack glass setup to be done as an addon-mod then rather than a direct edit to your mod?

**Comment by Xytabich** [comment]
Well, yes, the addon should be created. I don't know why you want to edit the mod itself :)

**Comment by kotoroshinoto** [comment]
that makes more sense then, i'd just have to upload it to the mod-db

**Comment by kotoroshinoto** [comment]
given how the mod assumes "glass-*" pattern in codes, does it ALSO check if the code exists as-is without prepending "glass-"?

Bricklayers has a set of colored glass blocks/items with the code pattern glasscolored-*
such as glasscolored-quartz-pink

**Comment by Xytabich** [comment]
I didn't quite understand where "glass-*" patterns are used and what do you want to do?
If you have a discord, then it's better to write to me there, you can find me on the official server of the game

**Comment by kotoroshinoto** [comment]
The examples don't seem to point at vanilla game:glass-plain, etc, at least
not automatically, unless the shorter names automatically supply the glass-
prefix somehow

Was it not intended to? The explanation doesn't make it clear on which was
the code value will be expanded or used to auto fill other parts or codes.

It mentions where it expects a texture and the name in lang not needing the
word glass.

Does it go any farther in the usage?

**Comment by Xytabich** [comment]
The mod uses an internal glass typing (coding) system, the glass codes themselves and their parameters are declared in `glasstype.json`. The full glass code consists of `MODID:CODE`. Textures are used from a predefined folder based on modid and glass code. To display the glass name in the gui, the `MODID:glassblend-CODE` code is used. In recipes where melted glass is used, `MODID:CODE` specifies the glass code, or just `CODE` if the glass and the recipe have the same modid.

**Comment by kotoroshinoto** [comment]
for instance the entries in this file: 

https://github.com/Xytabich/Glassmaking/blob/master/assets/game/worldproperties/abstract/glasstype.json

they're placed into assets/game/ which I suppose automatically supplies that they should be part of game:

however it doesn't use glass- prefixes in the codes for the blends.

I presume that means it won't map to the textures?

it seems a lot of the base game textures are mapped via paths like this:

\Vintagestory\assets\survival\textures\block\glass

**Comment by Xytabich** [comment]
Types are placed in `assets/game/` to have modid `game` because they are vanilla glass types. Textures are also taken from vanilla resources, if you look in the game folder, you can see in one of the subfolders that there are textures along this path. The `glass-` prefix does not appear anywhere, what makes you think that this prefix is needed somewhere?

**Comment by kotoroshinoto** [comment]
I was wondering mainly because they don't seem to have associated colors, the creative / helper menus show those dust piles are uniformly whitish/gray

**Comment by kotoroshinoto** [comment]
also, the blocks seem to have that prefix, I guess that only matters when the casting/blowing recipes are put in?

**Comment by Xytabich** [comment]
Blends have small inclusions of glass textures, but since they are translucent it's not always possible to see the color.
If you are talking about this recipe https://github.com/Xytabich/Glassmaking/blob/master/example%20assets/blocktypes/castmold.json, this is just an example of wildcards, for convenience, so as not to create a recipe each time separately for each color of the stack. These wildcards will only work if the item code has a part that matches the glass code.
