### ISSUE TITLE
Mold recipes with multiple modid/glasstypes?

### ISSUE THREAD

**Issue by kotoroshinoto** [Xytabich/Glassmaking#4]
looking at the example for casting and blowing molds, is there a way to make a single mold accept a set of glass types that are from different modid namespaces and direct the output accordingly? 

glass types would be within game: and otherid: in separate worldproperties/glasstype.json files, so the output would need to use appropriate modids and glass block codes, such as some to game:glass-* and some to otherid:otherglass-*?

if it doesn't work this way currently, maybe you could change it to mimic the way variantgroups works, having a hashtable/dictionary lookup within the glassmaking:castingmold attribute, something like recipeByType & outputByType

**Comment by kotoroshinoto** [comment]
if it doesn't , maybe you could change it to mimic the way variantgroups works, having a hashtable/dictionary lookup within the glassmaking:castingmold attribute, something like recipeByType & outputByType

**Comment by Xytabich** [comment]
You can use glass types from other modids, these recipes work the same as the vanilla recipes, except that the glass type code is used instead of the item code.

**Comment by kotoroshinoto** [comment]
can you show an example of how to do that in a single mold object using your recipe syntax?

like if I wanted to make a glass block mold that would take the game:glass-red and bricklayers:coloredglass-dark-red, etc and produce appropriate output block for each.

The glass codes would be game:red or bricklayers:dark_red

**Comment by Xytabich** [comment]
Ah, now i understand what you mean. Due to the fact that wildcards cannot be used in domain, mold can only be used for output items with the same modid.
Adding something like "outputByType" won't work since it's reserved, but it's possible to give the "glassmaking:castingmold" attribute the additional ability to assign multiple recipes as an array.

**Comment by kotoroshinoto** [comment]
that would be useful I think. It'd be a bit silly to need multiple molds to produce glass blocks for different mods.

I imagine it would be much the same for the glass blowing molds

**Comment by kotoroshinoto** [comment]
I imagine it would be much the same for the glass blowing molds

**Comment by Xytabich** [comment]
Added in version 1.3.2

**Comment by kotoroshinoto** [comment]
since it hasn't made its way into the wiki yet, how is the json structure expected to be formatted for multiple recipe entries?

do both the output and recipe each get an array, or does the attribute receive an array that each contain a dictionary/hashtable lookup containing "recipe" and "output"?

edit: I looked at the commit, I see the example casting mold now

**Comment by kotoroshinoto** [comment]
it seems like it kinda works. It allows me to attempt to put glass into the mold.

the base-game's glass blocks are forming, but when I put in molten glass for the bricklayer's block, the client crashes.

i'm not sure if I have done something improper or if something else is causing it.

the error said something about a key value can't be null

**Comment by Xytabich** [comment]
I need a stacktrace from vs logs, as well as the recipe attribute itself

**Comment by kotoroshinoto** [comment]
I found the problem. It was on my end, a plural vs singular misspelling in the path or name somewhere. 

I wish they were better about the error message content XD
