### ISSUE TITLE
removing glass remnants from the smelteries

### ISSUE THREAD

**Issue by kotoroshinoto** [Xytabich/Glassmaking#5]
is there a functionality / behavior pre-programmed into the smelteries to remove the remaining amounts after the ladle can no longer remove molten glass?

it looks like even the smallest ladle leaves 100 units behind. 

perhaps that is what you had in mind with the items representing glass chunks, pieces, shards?

**Comment by Xytabich** [comment]
You can break the smeltery to get glass shards, there is no other way. Those. it is planned in advance that one smeltery melts only one type of glass
